
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://omkhpyvxcgsyuiuhnxom.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ta2hweXZ4Y2dzeXVpdWhueG9tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyMDA2ODksImV4cCI6MjA2MTc3NjY4OX0.RKWg6sSrCxJp8KS15aNDWCEPiB7-LUCkScwyz4UedGE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
